### ISSUE TITLE
Issue with the top padding in <550px responsive mode

### ISSUE THREAD

**Issue by jimsefton** [v12mike/we_universal-1#10]
Small issue with the top padding in <550px responsive mode. In <500px mode the icons and dropdown menu are tight to the top, >550px mode there is some padding. I presume these should be the same?

Fixed as follows:

`@media only screen and (max-width: 550px) {
	.inventea-wrapper {
	    padding: 14px 5px 5px 5px;
    	}}`

**Comment by v12mike** [comment]
If I remember correctly (I made that change a while ago in my repo) it was intentional, to make maximum use of the screen width, but I will try it with your suggestion and see how it looks.  

I intend to try some other adjustments sub-550px before the next release, to improve the header behaviour.

**Comment by jimsefton** [comment]
Hi, its actually the height not width. Will leave it up to you, it’s easy enough to override in a custom css. Great work so far, really appreciate it!

**Comment by v12mike** [comment]
You are correct.  I have applied your change
