### ISSUE TITLE
Latest post icon missing

### ISSUE THREAD

**Issue by jimsefton** [v12mike/we_universal-1#12]
The latest unread post icon (small orange icon) that used to be just to the left of the topic title seems to be missing.

![iconorange](https://user-images.githubusercontent.com/1613164/36999599-88729f16-20b8-11e8-8581-e0b8c96f1170.jpg)

**Comment by v12mike** [comment]
That change was intentional, as the small icon was functionally duplicating the large icon just to the left of it, and the page looks cleaner without it.  With the standard icons, the colour denotes unread posts.

Do you have strong feelings about it?

**Comment by jimsefton** [comment]
My users are complaining about it. I think the issue is there is no way of telling if there are unread messages if you have logged out and back in. I registered for tour forum and all looked ok, but upon logout and logging back in all the icons on the left are grey (as expected) but there are no latest post icons so it just looks like all the topics have been completely read.

Does that make sense or am I missing something? Took a while to work out as I was wondering why php.com has the icon if it was purely a duplicate.

**Comment by jimsefton** [comment]
Just to clarify, I think the colour dictates unread posts since last login whereas the small icon is unread posts for that user but doesn’t worry about login/logout.

**Comment by v12mike** [comment]
On our forum, the unread posts icon is certainly a different colour, and read/unread is persistent across sessions, so I think that your primary problem is something else.  

I see above that you are not using the default icon, can you tell me how you configured yor icons, through the ACP, or by editing the style?  I think that there could be an issue if you are using bitmap icons rather than font icons.

**Comment by jimsefton** [comment]
Sorry, that screenshot was an old forum just to demonstrate what icon I am referring to. My main forum is z4-forum.com.

I am seeing the issue on your demo forum though, It looks at first glance like I have read everything. All icons are grey.

**Comment by v12mike** [comment]
I don't have a lot of confidence that that demo forum is configured correctly, can you look at our live forum frenchcarforum.co.uk

**Comment by v12mike** [comment]
I just registered on your forum, and most (but not all) forums show as having no unread topics.  I don't think that this is related to the style, I think that something else is wrong.  I wonder how it looks in prosilver.

**Comment by v12mike** [comment]
To clarify what I see on your forum is that if I click the "new posts" button, only 2 of the posts are shown as unread, all the others are marked as read, even though I haven't read them.

**Comment by jimsefton** [comment]
lol, very confusing. I must admit i used that icon all the time, but not sure if it's just down to muscle memory.

I have asked the question on phpbb.com, so hopefully we can get some clarity;

https://www.phpbb.com/community/viewtopic.php?f=556&t=2462716

I do agree it looks cleaner without, but I wonder considering the icon is a feature of most phpbb boards (and phpbb.com itself) whether it should be a toggle-able feature? I guess keeping it there and hiding the <span> would have the same effect, but allow it to be re-introduced via CSS?

**Comment by v12mike** [comment]
I could put it back as a hidden element, but I don't think that it would help anyone much.  We have been running this version since phpBB 3.2.0.
You could try putting back the original behaviour (viewforum.html around line 155), 
I believe that the previous arrangement (which prosilver still has) is an illogical historical artefact.

**Comment by jimsefton** [comment]
Cool. Happy to let it go if we get confirmation the behavior is the same. No point having duplicate functionality if we don't need it. I'll let you know if I find out any more info.

**Comment by jimsefton** [comment]
Just checked prosilver and it looks like you are right:

`<a href="{topicrow.U_NEWEST_POST}" class="row-item-link"></a>
					<div class="list-inner">
						
						
							<a class="unread" href="{topicrow.U_NEWEST_POST}">
								<i class="icon fa-file fa-fw icon-red icon-md" aria-hidden="true"></i><span class="sr-only">{NEW_POST}</span>
							</a>
						`

**Comment by jimsefton** [comment]
Confirmed by phpbb support :)

https://www.phpbb.com/community/viewtopic.php?f=556&t=2462716
