### ISSUE TITLE
Responsive header is not shown

### ISSUE THREAD

**Issue by janzev** [v12mike/we_universal-1#13]
The responsive header (like in prosilver or the former we_universal versions) is not shown. This is bad, if you have some custom links at your forum header. Already the standard links are not shown very nicely. I'm on the latest master branch. The screenshot comes from a nearly unmodified version of we_universal (only the header texts are not shown.
![grafik](https://user-images.githubusercontent.com/32398789/40281439-f9b79d2c-5c61-11e8-81aa-bbe6d9e91aa1.png)

**Comment by v12mike** [comment]
see: https://www.phpbb.com/customise/db/style/we_universal/faq/2571

**Comment by janzev** [comment]
Thanks. I will try it.
