### ISSUE TITLE
3.2.5

### ISSUE THREAD

**Issue by ghost** [v12mike/we_universal-1#14]
Is this theme going to be updated to 3.2.5?

**Comment by ghost** [comment]
Bump?

**Comment by v12mike** [comment]
There is not much reason for updating this style between minor phpBB version increments.
I am currently updating the style for phpBB 3.2.7.

**Comment by Stanzilla** [comment]
@v12mike this was a crucial change that had to happen, otherwise people could not login https://www.phpbb.com/community/viewtopic.php?t=2509981#p15243286

**Comment by v12mike** [comment]
I have not had any reports of users having problems without it upto and including phpBB3.2.7

I have added this code in we_universal v2.5.8-b1, although to be honest I did not realise the significance until now.

**Comment by Stanzilla** [comment]
Great, thank you!
