### ISSUE TITLE
Small Visual Problems with space and lines

### ISSUE THREAD

**Issue by panteror** [v12mike/we_universal-1#8]
Hi,
First, thank you very much to keep alive this wonderfull style.
I tested your new version for 3.2.2 this morning and i see some visual problem compare with 3.2.1.
Here the screenshot with my forum but it's same with your test forum https://xmv6.co.uk/
Comments are on the screeen.

![display pb 3 2 2](https://user-images.githubusercontent.com/13719235/36658598-94fd7f7c-1ad1-11e8-8375-71fa1a13293f.png)

here how it looks on my 3.2.1 forum
![original 3 2 1](https://user-images.githubusercontent.com/13719235/36658597-94b1ce9c-1ad1-11e8-9931-151462efed3b.png)

Thanks.

**Comment by v12mike** [comment]
OK, I see what you mean.  I will look into it.

**Comment by v12mike** [comment]
I have made a couple of minor adjustments in theme/content.css
See if the latest version on the master branch looks better to you.

**Comment by panteror** [comment]
Your commit fixed the row space between lines (purple comment in screen)

But no fix for space/blank before the beginning of text (red comment), in previous version there is like a tab before. it's same for index and viewforum.

**Comment by panteror** [comment]
Hi,

I did some test with chrome devtools, i tried to tweaks content.css.
If i put padding like this, it seems looking like 3.2.1. But I don't know if it's bad in other place with this change ? It's a new element that you added for 3.2.2.
```
ul.topiclist li.row dd {
	margin-bottom: 4px;
	padding: 7px;
}
```
NB: I see two references in content.css for ul.topiclist li.row dd ?
Line 74 and 95 normal ?

If it can help you.
Thanks

**Comment by v12mike** [comment]
Thankyou for your helpful comment.  I made a small mistake.  I intended to delete the lines
```
ul.topiclist li.row dd {
	margin-bottom: 4px;
	padding: 7px;
}
```
but somehow missed in the version that got checked in.  

I thought that the result  with just
```
ul.topiclist li.row dd {
	padding: 4px;
}
```
was satisfactory.

I don't generally intend that each release of we_universal will look absolutely identical to the previous one, but will try not to alter the look and feel without reason.  

I will probably make another releasein a few weeks when there has been more feedback.

**Comment by panteror** [comment]
ok thanks, it's better now even if it doesn't fit exactly like old version like you said.

**Comment by v12mike** [comment]
I see that your forum has little icons in the last message column.  Where do they come from?

**Comment by panteror** [comment]
it was in theme previous version, don't remember which number. I liked it but it was removed with 3.2.0 i think. It's font awesome icons. When you look screens here https://www.phpbb.com/customise/db/style/we_universal you can see those icons.
So i personalized theme templates/css to my own taste (no round corner, back of some icons) with my little skills.
My live forum is here (running 3.2.1) if you want to get a look http://www.dowfrance.com/

**Comment by Matevoun** [comment]
Thanks you very munch, @v12mike /// All seems worked fine for me ( http://forum.wda-fr.org ).
